### ISSUE TITLE
Text appears transparent in colored tectanle

### ISSUE THREAD

**Issue by AlbertoElias** [soimy/msdf-bmfont-xml#16]
I've been trying to create my own msdf fonts, based on Roboto which I fetched from Google Fonts. Using this tool and then loading it in Three.JS with https://github.com/Jam3/three-bmfont-text loads transparent text in a colored rectangle. It works fine if I load the pre generated Roboto from here: https://github.com/Jam3/three-bmfont-text/tree/master/test/fnt

Error:
<img width="734" alt="broken_font" src="https://user-images.githubusercontent.com/913117/34750347-efec99e0-f5a6-11e7-8cec-8069b7b15748.png">

I've tried both on Ubuntu and Windows and with multiple Roboto ttfs, and other fonts.

**Comment by soimy** [comment]
`three-bmfont-text` is old. Since https://github.com/Chlumsky/msdfgen Release v1.4 all generated channel have been reversed, and the MSDF shader should be updated accordingly.

You can check out https://github.com/soimy/msdf-bmfont-xml/tree/master/test for an example on how to use `msdf-bmfont-xml` generated atlas with `three-bmfont-text`

**Comment by AlbertoElias** [comment]
Great, thanks for the info. There seems to be a slight white border around all characters that makes it less legible. Is there a way to remove it? Thanks a lot!

**Comment by donmccurdy** [comment]
Fix proposed here: https://github.com/Jam3/three-bmfont-text/pull/24
